export const EXAMPLE_PATH = 'blog'
export const CMS_NAME = 'Home'
export const HOME_OG_IMAGE_URL =
  ''
export const BLOG_NAME = 'Jennifer'
export const KEYWORDS = 'Jennifer, Cpp, Chukwu, Rust, python, programming, Nigeria'
export const DESCRIPTION = 'Systems Programming || Machine Learning'
export const AUTHOR = 'Jennifer Chukwu'
export const LANG = 'en-CA'
export const GITHUB_REPO = 'https://github.com/jnyfah'